#!/bin/bash

# Update and install HAProxy
sudo apt update
sudo apt install -y haproxy

# Backup original config
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    option  httplog
    option  dontlognull
    timeout connect 5s
    timeout client  50s
    timeout server  50s
    retries 3

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 3.84.40.22:80 check
    server web-02 34.203.218.108:80 check
EOF

# Restart and enable HAProxy
sudo systemctl restart haproxy
sudo systemctl enable haproxy

echo "HAProxy setup complete. Load balancer is running."

